from __future__ import annotations
from .analysis import Insn, BasicBlock, pseudo_line

MODE_IDS={'imp':0,'acc':1,'imm':2,'zp':3,'zpx':4,'zpy':5,'rel':6,'indx':7,'indy':8,'abs':9,'absx':10,'absy':11,'ind':12}


def emit_reference_js(decoded:dict[int,Insn], blocks:dict[int,BasicBlock], states:dict[int,dict])->str:
    lines=[
        '// generated by nes2web',
        '// Static reference translation of reachable deterministic code.',
        '// This is for reverse engineering and future native backend work; the playable web build uses JSNES.',
        'export const blocks = {',
    ]
    for start in sorted(blocks):
        b=blocks[start]
        lines.append(f'  0x{start:04X}: function block_{start:04X}(cpu, mem) {{')
        lines.append('    let {A,X,Y,SP,C,Z,I,D,V,N} = cpu;')
        for addr in b.instructions:
            p=pseudo_line(decoded[addr],states.get(addr))
            lines.append(f'    // ${addr:04X}  {decoded[addr].text()}')
            lines.append('    // '+p)
        succ=', '.join(f'0x{x:04X}' for x in b.successors)
        lines.append(f'    return [{succ}];')
        lines.append('  },')
    lines.append('};')
    lines.append('')
    return '\n'.join(lines)


def emit_wat(decoded:dict[int,Insn], blocks:dict[int,BasicBlock])->str:
    '''Emit valid WAT-shaped static block module using an imported semantic executor.

    It hardcodes decoded opcodes/operands and therefore removes ROM opcode fetching/decoding,
    but deliberately leaves exact CPU/bus semantics in an import until a full native backend exists.
    '''
    lines=[
        ';; generated by nes2web',
        ';; experimental static-recompiler backend',
        ';; host exec(pc, opcode, operand, mode_id) -> next_pc performs exact 2A03/bus semantics',
        '(module',
        '  (import "nes" "exec" (func $exec (param i32 i32 i32 i32) (result i32)))',
    ]
    for start in sorted(blocks):
        b=blocks[start]
        lines.append(f'  (func $block_{start:04X} (result i32)')
        lines.append('    (local $next i32)')
        for addr in b.instructions:
            ins=decoded[addr]
            operand=ins.operand if ins.operand is not None else -1
            mode=MODE_IDS.get(ins.mode,0)
            lines.append(f'    i32.const {addr}')
            lines.append(f'    i32.const {ins.opcode}')
            lines.append(f'    i32.const {operand}')
            lines.append(f'    i32.const {mode}')
            lines.append('    call $exec')
            lines.append('    local.set $next')
        lines.append('    local.get $next')
        lines.append('  )')
        lines.append(f'  (export "block_{start:04X}" (func $block_{start:04X}))')
    lines.append(')')
    return '\n'.join(lines)+'\n'
